//! Data models for the trading system

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Asset type (stock or cryptocurrency)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum AssetType {
    Stock,
    Crypto,
}

/// Market data for an asset
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketData {
    pub id: String,
    pub symbol: String,
    pub name: String,
    pub asset_type: AssetType,
    pub price: f64,
    pub volume: f64,
    pub timestamp: DateTime<Utc>,
}

impl MarketData {
    pub fn new(symbol: String, name: String, asset_type: AssetType, price: f64) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            symbol,
            name,
            asset_type,
            price,
            volume: 0.0,
            timestamp: Utc::now(),
        }
    }
}

/// Trading signal generated by a strategy
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum Signal {
    Buy,
    Sell,
    Hold,
}

/// A trading strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Strategy {
    pub id: String,
    pub name: String,
    pub description: String,
    pub asset_type: AssetType,
    pub enabled: bool,
    pub created_at: DateTime<Utc>,
}

impl Strategy {
    pub fn new(name: String, description: String, asset_type: AssetType) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            name,
            description,
            asset_type,
            enabled: true,
            created_at: Utc::now(),
        }
    }
}

/// Trade order
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum OrderType {
    Market,
    Limit,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum OrderSide {
    Buy,
    Sell,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum OrderStatus {
    Pending,
    Filled,
    Cancelled,
    Failed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    pub id: String,
    pub symbol: String,
    pub asset_type: AssetType,
    pub order_type: OrderType,
    pub side: OrderSide,
    pub quantity: f64,
    pub price: Option<f64>,
    pub status: OrderStatus,
    pub created_at: DateTime<Utc>,
    pub filled_at: Option<DateTime<Utc>>,
}

impl Order {
    pub fn new_market(symbol: String, asset_type: AssetType, side: OrderSide, quantity: f64) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            symbol,
            asset_type,
            order_type: OrderType::Market,
            side,
            quantity,
            price: None,
            status: OrderStatus::Pending,
            created_at: Utc::now(),
            filled_at: None,
        }
    }
}

/// API response wrapper
#[derive(Debug, Serialize, Deserialize)]
pub struct ApiResponse<T> {
    pub success: bool,
    pub data: Option<T>,
    pub error: Option<String>,
}

impl<T> ApiResponse<T> {
    pub fn ok(data: T) -> Self {
        Self {
            success: true,
            data: Some(data),
            error: None,
        }
    }

    pub fn err(error: String) -> Self {
        Self {
            success: false,
            data: None,
            error: Some(error),
        }
    }
}
